version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: pix_reaction_db
    environment:
      POSTGRES_USER: 'pst_user'
      POSTGRES_PASSWORD: 'pstservice123'
      POSTGRES_DB: 'pst_db'
    volumes:
      - ./data/pix_reaction_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_overlay

networks:
  backend_overlay:
    driver: bridge
    attachable: true

volumes:
  pix_reaction_db:
